### ISSUE TITLE
Check if occupancy in `emissions_factors.csv` is in percent or in number of people

### ISSUE THREAD

**Issue by han16nah** [pledge4future/co2calculator#109]
If it is in percent, check entries:

,category,subcategory,source,model,name,unit,size_class,occupancy,capacity,range,fuel_type,co2e_unit,co2e,seating,comment
68,transport,train,Öko-Institut,gemis,Zug-Personen-Fern-Diesel-DE-2020-Basis,P.km,,500,,long-distance,diesel,kg/P.km,0.044,,
69,transport,train,Öko-Institut,gemis,Zug-Personen-Fern-Elektro-DE-2020-Basis,P.km,,750,,long-distance,electric,kg/P.km,0.00948,,

**Comment by veitu** [comment]
It's in number of people for all entries except for the buses from tremod, so for the buses from tremod I converted them to number of people (directly in the dev branch). If that's fine, I guess the issue can be closed.

**Comment by han16nah** [comment]
Changed all to percent, to be merged soon #107
