### ISSUE TITLE
Adapt flight emissions calculation

### ISSUE THREAD

**Issue by veitu** [pledge4future/co2calculator#112]
It seems strange that our calculated emissions tend to be lower for flying than they are for driving. After doing again some research on emission factors for flights, I would suggest to stick with the DEFRA emission factors that we are using for flights, because:
- there are huge differences between different flight emission calculators (the calculated emissions vary 4-fold)
- much of the variation comes from different estimates of the influence of radiative forcing, and this is very uncertain
- the DEFRA emission factors are roughly in the middle between ICAO (lowest emission estimate) and Atmosfair (highest estimate)
- the DEFRA emission factors seem to be the most comprehensive set of emission factors available for flights
- they are published by a government agency (more trustworthy than a private company) with a transparent methodology and updated annually

However, I would suggest to change the following things:
- Right now we are only using EF's for short haul and long haul flights. I suggest to use the 'domestic' EF for all flights below 700 km, because it is much higher than the short haul EF's. I guess we are not using it atm because it only has the seating class "average", but I think it is still more adequate for very short flights than the short haul EF's.
- [This calculator](https://flygrn.com/blog/carbon-emission-factors-used-by-flygrn) also uses the 'domestic' EF for flights below 700 km.
- I don't know why we use the distance of 1500 km to separate short haul and long haul, but we might change the threshold to 3700 km because this is stated in the DEFRA methodology paper.
- Also, we might want to update the flight emission factors, because they have been updated in the DEFRA database.
- add first class option for long haul flights

**Comment by han16nah** [comment]
Sounds good, I agree with your suggestions, so feel free to implement them.


Side note: It's probably also realistic, that (some) cars - if only occupied by one person - come close to planes or are sometimes even higher.

On Quarks (which have [this CO2 calculator](https://www.quarks.de/umwelt/klimawandel/co2-rechner-fuer-auto-flugzeug-und-co/)), they say the following about this:

**"Mein Ergebnis ist seltsam. Woram könnte das liegen?**
*Bei einigen Verkehrsmitteln mögen die CO2-Werte auf den ersten Blick überraschen. So kann im CO2-Vergleich die Fahrt mit einem alten und großen Benziner mit nur einer Person auf der Strecke von 250 Kilometern (64 Kilogramm CO2) den eines Flugzeugs (52 Kilogramm CO2) sogar übertreffen. Und das, obwohl Flugzeuge als besonders klimaschädlich bekannt sind.*

*Grund dafür ist die Auslastung: Flugzeuge sind im Mittel sehr gut ausgelastet, also relativ voll besetzt. Deshalb schneidet ein großer alter Pkw mit nur einem Insassen bei diesem Beispiel schlechter ab – die Ergebnisse beziehen sich ja stets auf eine Person.*

*Fahrten mit dem ÖPNV ergeben wiederum häufig vergleichsweise hohe CO2-Werte. Auch hier liegt es meist an der Zahl der reisenden Personen: Sieht man einmal vom Pkw ab, hat der ÖPNV im Verkehrsmittelvergleich die geringste Auslastung. Hintergrund: Beim ÖPNV gelten Fahrzeuge erst dann als vollkommen ausgelastet, wenn neben den Sitzplätzen auch alle Stehplätze genutzt werden."*

**Comment by han16nah** [comment]
This could also be interesting! https://www.easa.europa.eu/en/domains/environment/icao-aircraft-engine-emissions-databank

**Comment by redfrexx** [comment]
If possible also look into co2 factors of different airlines. GI said this would be helpful to them when planning a trip. Check out how google does it.
