### ISSUE TITLE
Setup pipelines and deployments

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/co2calculator#159]
Basic task collections for package setup: 

- [x] setup build pipeline
- [x] setup tests pipeline
- [x] setup automated deployment of documentation to GitHub Pages
- [x] setup release job for package
- [x] setup deployment to PyPi and TestPyPi
- [x] Setup Publishing Job
- [x] Add Support for more python versions
- [x] Create Report for test coverage

**Comment by redfrexx** [comment]
I guess we can close this once we've enabled the push to pypi.

**Comment by codingfabi** [comment]
Closed it since deploying version 1.0 to pypi would be a different task I think.
