### ISSUE TITLE
Enhance Error Handling

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/co2calculator#161]
We should validate and intercept certain user inputs and also prevent crashes by throwing verbose exception. Some Ideas: 

- [x] Define invalid combinations of function parameters (e.g. `transportationMode="plane"` and `fuelType="diesel"`). We should write an evaluation util function for this that checks for certain, obvious/common combinations that do not make sense (see also: #137).
- [x] Throw `UnknownEmissionFactor` exception when no EmissionFactor is found. 
- [x] Throw exception on Unknown parameters (Unknown transportation mode or unknown fueling type)
- [ ] Handle common routing exceptions:
       - [ ] Invalid ORS key
       - [ ] Invalid Latitude/Longitude input
       - [ ] Adress not found

**Comment by redfrexx** [comment]
Improved error handling related to parameter combinations for emission factors in #173 . Improvement of error handling related to routing is now continued in new issue #189 .
