### ISSUE TITLE
Find solution to run ORS tests on github

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/co2calculator#51]
Figure out how we could run the tests involving a request to the openrouteservice in the automated tests run on github.

**Comment by han16nah** [comment]
I think GitHub's "encrypted secrets" is what we're looking for! @redfrexx 
https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by han16nah** [comment]
We now have an "encrypted secret" witht the ORS API key. It was created at the organization level and currently only available to the `co2calculator` repository. This secret is used as environment variable when running our pytests in GitHub action.
