### ISSUE TITLE
write code for multimodal commuting/business trips

### ISSUE THREAD

**Issue by sarahmadeleine** [pledge4future/co2calculator#94]

**Comment by han16nah** [comment]
Isn't this rather something for the backend/frontend?

A multimodal business trip would simply mean summing up separate business trips for different modes of transport, e.g. Heidelberg -> Frankfurt by train, Frankfurt -> London plane, etc. In a Web App, we can of course make sure that we have a form that allows specifiyng a multimodal business trip easily. 

For commuting, our approach was to provide the weekly distance for each mode of transport, so if I commute by a combination of bike and train (say: 4 km by bike each day and 16 by train), I would simply put 20 km for bike and 80 km by train.

**Comment by alexbercik** [comment]
This is something that would need to figure out directly with the frontend/backend, also for example for trips between cities. We would need a way to account for layovers between cities (etc. train, plane), and while that is frontend/backend, we have to be smart about selecting the proper emission factors if we leave a certain region or country. For example intercity trains can have different values between different countries. Do we use the country of origin or destination? I think we should have this conversation at a future meeting. This will be important as well for the trip estimator / planner feature.
